### ISSUE TITLE
Graves exploding

### ISSUE THREAD

**Issue by drewberni** [LCLPYT/LCLPGraveStones#1]
This is a great plugin and I love the simplicity of it however the code preventing the chest from exploding doesn’t seem to work. Creepers tnt and beds in other dimensions can still blow the chest up on death causing item loss

**Comment by LCLPYT** [comment]
Thank you for reporting this. It will be fixed in version 1.1 (not available yet on dev.bukkit.org; until it is approved, you may download it from the GitHub releases) -> [download](https://github.com/LCLPYT/LCLPGraveStones/releases/latest/download/LCLPGraveStones.jar)

**Comment by drewberni** [comment]
thx so much
